# Machine Learning Credit Score

Objetivo desse projeto conjunto com a Alura é entender como o Machine Learning está no mercado financeiro, quais sao aas particularidades desse setor e como construir, ajustar e escolher a melhor regressao logistica, será usada como motor na concessao de crédito do *ByteBank*, um banco digital.

Esse projeto é para entender como é usado os algoritmo por trás das decisoes das instituicaoes financeiras.

### Ciclo da Concessao de Crédito e risco associados

O crédito faz parte das nossas vidas o tempo todo: cartões de crédito, empréstimos pessoais e consignados, financiamento de veículos e imobiliários, são apenas alguns dos exemplos de como o crédito está inserido no nosso dia a dia.

Apesar disso poucas pessoas sabem quais sao as decisoes que sao tomadas por trás da concessao de credito. 

A decisoes é composta pela cadeia de credito que é composta por quatro pilares: **A Prospecacao, a Concessao, a Gestao de Risco e a Recuperacao.**

 O Crediting Score, ele busca estimar a probabilidade de um evento acontecer frente a uma base de dados. Estamos falando de uma probabilidade, então o valor está concentrado entre 0 e 1.
 
 Pensando na concessão de crédito, o evento que nós estamos buscando é se um tomador vai ser inadimplente ou nao e isso é um evento binario.

 Toda concessao de crédito está  intrinsecamente relacionada ao risco.

 Podemos entender o risco de crédito como a probabilidade de receber um montante de dinheiro em um determinado período nao acontecer.

#### Conhecendo o Dataset

In [112]:
import pandas as pd

In [113]:
# Base de dados de crédito
url = 'https://raw.githubusercontent.com/alura-cursos/credit_scoring/main/base_dados_traduzida.csv'
dados = pd.read_csv(url)
dados.head()

,default,conta_corrente,prazo_emprestimo_meses,historico_credito,proposito_emprestimo,valor_emprestimo,reserva_cc,tempo_emprego_atual,taxa_comp_salario,sexo_est_civil,...,anos_residencia_atual,propriedade,idade,outros_planos_financiamento,tipo_residencia,n_creditos_banco,status_emprego,n_dependentes,telefone,trabalhador_estrangeiro
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

In [114]:
# Informacoes da Base de dados
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   default                      1000 non-null   int64
 1   conta_corrente               1000 non-null   object
 2   prazo_emprestimo_meses       1000 non-null   int64
 3   historico_credito            1000 non-null   object
 4   proposito_emprestimo         1000 non-null   object
 5   valor_emprestimo             1000 non-null   int64
 6   reserva_cc                   1000 non-null   object
 7   tempo_emprego_atual          1000 non-null   object
 8   taxa_comp_salario            1000 non-null   int64
 9   sexo_est_civil               1000 non-null   object
 10  outros_fiadores              1000 non-null   object
 11  anos_residencia_atual        1000 non-null   int64
 12  propriedade                  1000 non-null   object
 13  idade                        1000 non-null   int64
 14  outros_planos_financiamento  1000 non-null   object
 15  tipo_residencia              1000 non-null   object
 16  n_creditos_banco             1000 non-null   int64
 17  status_emprego               1000 non-null   object
 18  n_dependentes                1000 non-null   int64
 19  telefone                     1000 non-null   object
 20  trabalhador_estrangeiro      1000 non-null   object
dtypes: int64(8), object(13)
memory usage: 164.2+ KB

In [115]:
# Quantidade de linhas e colunas
dados.shape

(1000, 21)

In [116]:
# Verificando se existem valores duplicados
dados.duplicated().sum()

0

In [117]:
# Verificando se existem valores nulos
dados.isnull().sum()

default                        0
conta_corrente                 0
prazo_emprestimo_meses         0
historico_credito              0
proposito_emprestimo           0
valor_emprestimo               0
reserva_cc                     0
tempo_emprego_atual            0
taxa_comp_salario              0
sexo_est_civil                 0
outros_fiadores                0
anos_residencia_atual          0
propriedade                    0
idade                          0
outros_planos_financiamento    0
tipo_residencia                0
n_creditos_banco               0
status_emprego                 0
n_dependentes                  0
telefone                       0
trabalhador_estrangeiro        0
dtype: int64

O Credit Scoring é um modelo estatístico multivariado que cria um modelo matemático e estima, através de uma probabilidade, a chance do nosso cliente ser adimplente ou inadimplente.

**CLASSIFICACAO**

O *ByteBank* precisa classificar os tomadores em bons e maus pagadores. Existem alguns algoritmos que são capazes de fazer essa classificação, por exemplo: a regressão logística, o random forest, Naive Bayes, support vector machine.

Vamos explorar a regressao Logistica. Ela é uma técnica muito usada no sistema financeiro e existem alguns motivos para isso. O primeiro deles é que ela tem um alto comprometimento com a explicabilidade, além de exigir pouco poder computacional.

In [118]:
dados.head()

,default,conta_corrente,prazo_emprestimo_meses,historico_credito,proposito_emprestimo,valor_emprestimo,reserva_cc,tempo_emprego_atual,taxa_comp_salario,sexo_est_civil,...,anos_residencia_atual,propriedade,idade,outros_planos_financiamento,tipo_residencia,n_creditos_banco,status_emprego,n_dependentes,telefone,trabalhador_estrangeiro
0,0,< 0 DM,6,critical account/ other credits existing (not ...,domestic appliances,1169,unknown/ no savings account,.. >= 7 years,4,male : single,...,4,real estate,67,none,own,2,skilled employee / official,1,"yes, registered under the customers name",yes
1,1,0 <= ... < 200 DM,48,existing credits paid back duly till now,domestic appliances,5951,... < 100 DM,1 <= ... < 4 years,2,female : divorced/separated/married,...,2,real estate,22,none,own,1,skilled employee / official,1,none,yes
2,0,no checking account,12,critical account/ other credits existing (not ...,(vacation - does not exist?),2096,... < 100 DM,4 <= ... < 7 years,2,male : single,...,3,real estate,49,none,own,1,unskilled - resident,2,none,yes
3,0,< 0 DM,42,existing credits paid back duly till now,radio/television,7882,... < 100 DM,4 <= ... < 7 years,2,male : single,...,4,if not A121 : building society savings agreeme...,45,none,for free,1,skilled employee / official,2,none,yes
4,1,< 0 DM,24,delay in paying off in the past,car (new),4870,... < 100 DM,1 <= ... < 4 years,3,male : single,...,4,unknown / no property,53,none,for free,2,skilled employee / official,2,none,yes

Pré-Processamento dos Dados para transformar a variaveis categoricas, para numericas

In [119]:
# Identificar colunas categóricas (excluido a variavel resposta 'Default')

colunas_categoricas = dados.select_dtypes(include=['object']).columns

# Aplicando transformacao ordinal

from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
dados[colunas_categoricas] = ordinal_encoder.fit_transform(dados[colunas_categoricas])

dados.head()

,default,conta_corrente,prazo_emprestimo_meses,historico_credito,proposito_emprestimo,valor_emprestimo,reserva_cc,tempo_emprego_atual,taxa_comp_salario,sexo_est_civil,...,anos_residencia_atual,propriedade,idade,outros_planos_financiamento,tipo_residencia,n_creditos_banco,status_emprego,n_dependentes,telefone,trabalhador_estrangeiro
0,0,1.0,6,1.0,4.0,1169,4.0,0.0,4,3.0,...,4,2.0,67,1.0,1.0,2,1.0,1,1.0,1.0
1,1,0.0,48,3.0,4.0,5951,1.0,2.0,2,0.0,...,2,2.0,22,1.0,1.0,1,1.0,1,0.0,1.0
2,0,3.0,12,1.0,0.0,2096,1.0,3.0,2,3.0,...,3,2.0,49,1.0,1.0,1,3.0,2,0.0,1.0
3,0,1.0,42,3.0,7.0,7882,1.0,3.0,2,3.0,...,4,0.0,45,1.0,0.0,1,1.0,2,0.0,1.0
4,1,1.0,24,2.0,2.0,4870,1.0,2.0,3,3.0,...,4,3.0,53,1.0,0.0,2,1.0,2,0.0,1.0

In [120]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   default                      1000 non-null   int64
 1   conta_corrente               1000 non-null   float64
 2   prazo_emprestimo_meses       1000 non-null   int64
 3   historico_credito            1000 non-null   float64
 4   proposito_emprestimo         1000 non-null   float64
 5   valor_emprestimo             1000 non-null   int64
 6   reserva_cc                   1000 non-null   float64
 7   tempo_emprego_atual          1000 non-null   float64
 8   taxa_comp_salario            1000 non-null   int64
 9   sexo_est_civil               1000 non-null   float64
 10  outros_fiadores              1000 non-null   float64
 11  anos_residencia_atual        1000 non-null   int64
 12  propriedade                  1000 non-null   float64
 13  idade                        1000 non-null   int64
 14  outros_planos_financiamento  1000 non-null   float64
 15  tipo_residencia              1000 non-null   float64
 16  n_creditos_banco             1000 non-null   int64
 17  status_emprego               1000 non-null   float64
 18  n_dependentes                1000 non-null   int64
 19  telefone                     1000 non-null   float64
 20  trabalhador_estrangeiro      1000 non-null   float64
dtypes: float64(13), int64(8)
memory usage: 164.2 KB

Separacao Treino e Teste

In [137]:
y = dados['default']
X = dados.drop('default', axis = 1)

In [155]:
from sklearn.model_selection import train_test_split

SEED=77 # semente para reprodução dos resultados
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state =SEED)

base_treino =  X_train.shape[0]
base_teste = X_test.shape[0]

print("Treinaremos com %d elementos e testaremos com %d elementos" % (base_treino, base_teste))

Treinaremos com 700 elementos e testaremos com 300 elementos

Modelo de Regressao logistica

In [154]:
# Treinando o modelo com Logistic Regression
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression(max_iter = 1000)

# Treinando o modelo com a base de treino
modelo.fit(X_train, y_train)
modelo.score(X_train, y_train)

# Avaliando o modelo com a base de treino
print("A acurácia do modelo é: %.2f%%" % (modelo.score(X_train, y_train)*100))

A acurácia do modelo é: 72.71%

d:\app\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [151]:
# Previsões
previsoes = modelo.predict(X_test)
previsoes

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [152]:
from sklearn.metrics import accuracy_score
acuracia = accuracy_score(y_test, previsoes)
acuracia = round(acuracia, 3)*100

print("A acurácia do modelo é: %.2f%%" % acuracia)

A acurácia do modelo é: 74.00%